version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:5000"
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
    command: ["python", "app.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"  # Port corrigé pour correspondre à Vite
    depends_on:
      - backend
